version: '3'
services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - dbdata:/var/lib/mysql/

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    restart: unless-stopped

  php-fpm:
    build: ./devops/docker
    container_name: php-fpm
    working_dir: /var/www
    restart: unless-stopped
    tty: true
    volumes:
      - ./codebase:/var/www

  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /var/www
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./codebase:/var/www
      - ./devops/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./devops/logs/nginx/:/var/log/nginx

  init-symfony:
    build: ./devops/docker
    container_name: init-symfony
    volumes:
      - ./:/home
    depends_on:
      - php-fpm
      - nginx
      - mysql
    command:
      - /home/devops/script/wait-for-mysql-up.sh

volumes:
  dbdata:
    driver: local