# Read the documentation: https://symfony.com/doc/3.0/bundles/FOSRestBundle/index.html
# bin/console config:dump-reference fos_rest
fos_rest:
    routing_loader: 
        default_format: json
        include_format: false
    body_listener: true
    format_listener:
        rules:
            - { path: ^/, prefer_extension: false, fallback_format: json, priorities: [ json ] }
    param_fetcher_listener:  true
    access_denied_listener:
        json: true
    view:
        view_response_listener:  'force'
        formats:
            json: true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
